### ISSUE TITLE
Commnets

### ISSUE THREAD

**Issue by gitcheol** [starry99/catbook#1]
Hello! Thanks you to ur serving this catbook git blog tool.! 
i have some trouble in using this. 
i wanna use the comment function in my blog but that`s not applied to my posts. 
---
title:
categories:
*comments: true *. <--this part
---
how can i activate the comment function in my github blog?

thank you!

**Comment by starry99** [comment]
Hi, did you register your site with DISQUS? Then, open your `config.yml` file and change `disqus_shortname`

**Comment by gitcheol** [comment]
Oh i did not know the DISQUS, now i registered the web!! 
it is really nice!! working well! thank you~
